### ISSUE TITLE
【建议】 可否把 Logo 的动画取消 + 换个位置

### ISSUE THREAD

**Issue by notHide** [xcanwin/KeepChatGPT#30]
1. Logo 那个闪光的动画有点喧宾夺主，注意力经常被吸引过去

2.左上角的 Logo 跟会话历史列表在同一列，而因为 Logo 要加载得慢一点，所以每次列表都有一个跳变。

当我点击左边任意历史会话，会话列表的位置都会先跳到上面（因为 Logo 没加载出来），然后列表又跳回来（Logo 加载完成）

每次点击都挺难受的。。可以考虑优化一下展示。

**Comment by Lete114** [comment]
看看这个？自己写的
https://github.com/Lete114/my-tampermonkey-scripts/blob/main/openai/chat/auto-reload.user.js

**Comment by caoshengdong** [comment]
非常支持，尤其是动画取消，对于 ADHD 来说，真的压力很大。。。

**Comment by VinsenHu** [comment]
位置倒还能接受，但是动画确实有点感官不太好

**Comment by chenwusheng7746** [comment]
哪个动画太难受了,晃得我眼晕

**Comment by Ezra-Chan** [comment]
不要动画的话，去掉下面这些代码：
```css
#kcg::before {
    content: '';
    position: absolute;
    top: -50%;
    left: -50%;
    width: 200%;
    height: 200%;
    background: linear-gradient(
        to bottom right,
        rgba(255, 255, 255, 0.3),
        rgba(255, 255, 255, 0.15),
        rgba(255, 255, 255, 0)
    );
    transform: rotate(-45deg);
    animation: shine 2.8s linear infinite;
}
@keyframes shine {
    from {
        transform: translateX(-50%) translateY(-50%) rotate(-45deg);
    }
    to {
        transform: translateX(150%) translateY(150%) rotate(-45deg);
    }
}
```
